### ISSUE TITLE
Create test case for enforcing valid links

### ISSUE THREAD

**Issue by codingo** [disclose/disclose#165]
As we add more links and this is subject to change over time a test case should be deployed to ensure that all links within the repository are valid at each instance when a new pull request is created

**Comment by JOSHUAJEBARAJ** [comment]
Hello Codingo Is it ok to use the travis ci

**Comment by codingo** [comment]
@JOSHUAJEBARAJ the core goal here is to limit external dependencies and I believe this could be handled in Github actions. If not and you can prove that I'd be quite open to Travis CI.

**Comment by JOSHUAJEBARAJ** [comment]
Cool The issue I don't have experience with Github Action Also the the tool check based on the test case is it ok

**Comment by JOSHUAJEBARAJ** [comment]
![image](https://user-images.githubusercontent.com/19353065/79953830-1e83b700-849a-11ea-9392-03b90d22952f.png) You will get the similar output is this you want to achieve

**Comment by whiteroses** [comment]
I think I got it working with GitHub Action: https://github.com/disclose/disclose/pull/185. Is this what you  are looking for?
