### ISSUE TITLE
You link Wrong responsible disclosure program 

### ISSUE THREAD

**Issue by imyatin** [disclose/disclose#206]
Hi Team,

I submit these to bugcrowd they replied 

"If you'd like to make your contributions there and mention this submissions id"

My submission id :- https://bugcrowd.com/submissions/006b732c015aedaad89952024774058a0f7d395c30ec92fa3db0d5f10754b15e

So these are the program which wrong link

1. ABNAMRO BANK   It will redirect to Royal Bank of Scotland [https://personal.rbs.co.uk/personal/fraud-and-security/responsible-disclosure.html] which is not of ABNAMRO BANK

   2. The ABNAMRO BANK responsible disclosure [https://www.abnamro.com/en/footer/responsible-disclosure.html]

3.    Lumosity program link to Lookout program [https://www.lookout.com/legal/responsible-disclosure]

  4.  Tin foil program link to TION group also TION group point to Tin foil

  5.  Edmodo point to Bugcrowd [https://www.bugcrowd.com/bug-bounty-list/]

  6.  Bime is point out to other but it's real program on hackerone [https://hackerone.com/bime]

Thanks

**Comment by codingo** [comment]
@imyatin addressing what I can here, please raise independent issues for other items:

1. fixed with #210 
2. Updating to:

```
  {
    "program_name": "Lumosity",
    "policy_url": "https://www.lumosity.com/en/legal/responsible_disclosure_policy/",
    "submission_url": "disclosure@lumoslabs.com",
    "launch_date": "",
    "bug_bounty": false,
    "swag": false,
    "hall_of_fame": false,
    "safe_harbor": "none"
  },
```

3. Unable to resolve either
4. This looks like a fp, or we already corrected it:

```
  {
    "program_name": "Edmodo",
    "policy_url": "",
    "submission_url": "privacy@edmodo.com",
    "launch_date": "",
    "bug_bounty": false,
    "swag": true,
    "hall_of_fame": false,
    "safe_harbor": ""
  },
```

5. This is correct, per: https://www.zendesk.com/company/policies-procedures/responsible-disclosure-policy/
