### ISSUE TITLE
Sort entries in bug-bounty-list.json

### ISSUE THREAD

**Issue by 0xdevalias** [disclose/disclose#22]
While it probably doesn't matter much from a programmatic sense, having the entries sorted would be nice from a human sense.

Using something like [jq](https://stedolan.github.io/jq/), this would be as easy as (note: piping could probably be better.. doing it directly seemed to clobber the end file, but i'm sure that's easilysolvable):

```
cat bug-bounty-list.json | jq 'sort_by(.program_name)' --raw-output > bug-bounty-list2.json
mv bug-bounty-list2.json bug-bounty-list.json
```

**Comment by jeffboothby** [comment]
Sorted!
