### ISSUE TITLE
Consider adding platform name to the list schema

### ISSUE THREAD

**Issue by nightwatchcyber** [disclose/disclose#51]
For many researchers, it would be interesting to know if a particular program is running on a platform such as HackerOne, BugCrowd, etc. We are proposing that the list schema be augmented with a new field to indicate the platform.

**Comment by yesnet0** [comment]
If a program is running with a platform, and many aren't, the platform in use is easily derived from "submission_url".

**Comment by nightwatchcyber** [comment]
That isn't true, some of the ones I added in #52 are being hosted at the company's site but are run as part of a platform.

For example:
- Lyft -> HackerOne
- PersonalCapital -> BugCrowd
-> Punchh -> BugCrowd

Here are some other examples from the existing list:
- Dominos -> Synack

See my blog post as to why this happens:
https://wwws.nightwatchcybersecurity.com/2019/05/04/finding-unlisted-public-bounty-programs-with-google-dorks/
