### ISSUE TITLE
Adopt industry standard term: coordinated disclosure

### ISSUE THREAD

**Issue by wireghoul** [disclose/disclose#53]
The term responsible disclosure has a long history of being used to strong arm security researchers by vendors. The security industry has largely settled on the use of coordinated disclosure and I recommend that this repo follow suit.

**Comment by yesnet0** [comment]
Thanks Eldar. We've standardized on Vulnerability Disclosure as the umbrella descriptive term. We'll take a pass through the repo to make sure that any instances of Responsible Disclosure, possibly carried over from the original FOSS disclosure project that was the precursor to disclose.io, are updated.
