### ISSUE TITLE
s/bug_bounty/vulnerability_disclosure_program/g

### ISSUE THREAD

**Issue by ahouseholder** [disclose/disclose#62]
Many of the programs listed in bug_bounty_list.json are not actually bug bounties (they don't offer payment). They'd be more accurately described as vulnerability disclosure (programs|services) or something like that. Bug bounties are a kind of vdp, but not the only kind represented in your list.

**Comment by yesnet0** [comment]
Good call. We went with "bug bounty" as the more broadly understood/know term, but you're absolutely correct wrt technical accuracy. We'll flush out a few technical dependancies and make the change.

**Comment by yesnet0** [comment]
@bcdavidchou Any update on this?
