### ISSUE TITLE
Altilly - https://www.altilly.com/page/bounty gives 404 page

### ISSUE THREAD

**Issue by bugbaba** [disclose/disclose#63]
Hey,

 The Altilly program at https://github.com/disclose/disclose/blob/master/bug-bounty-list/bug-bounty-list.json#L463 is giving 404 page.

they do have a security page https://www.altilly.com/page/security stating they do have a bugbounty program but no further details are given.

--
Regards,
Bugbaba

**Comment by jeffboothby** [comment]
Latest commit updated the details for Altilly.
