### ISSUE TITLE
HR Partner - has stopped thier bugbounty program

### ISSUE THREAD

**Issue by bugbaba** [disclose/disclose#64]
The HR Partner program at https://github.com/disclose/disclose/blob/master/bug-bounty-list/bug-bounty-list.json#L3213

has stopped their program as mentioned in their security page

https://www.hrpartner.io/security.html

> NOTE: We currently DO NOT have a bug bounty programme in place

--
Regard,
Bugbaba

**Comment by jeffboothby** [comment]
Latest update changed HR Partner's details for "bug_bounty" from true to false.
