### ISSUE TITLE
'Read the Core Terms' on homepage is broken

### ISSUE THREAD

**Issue by JLLeitschuh** [disclose/disclose#77]
The link on the homepage links to https://github.com/disclose/disclose/blob/master/core_terms and that link no longer works.

**Comment by llausa** [comment]
Hi, it's still broken:
<img width="703" alt="Screen Shot 2019-09-10 at 16 14 00" src="https://user-images.githubusercontent.com/19249080/64588545-074df880-d3e6-11e9-89ad-a8fa30c73c76.png">

**Comment by klepas** [comment]
Fixed in https://github.com/disclose/disclose/pull/79 :)
