### ISSUE TITLE
Logo resources

### ISSUE THREAD

**Issue by knightpfhor** [disclose/disclose#9]
The readme talks about "Organizations displaying the disclose.io logo".  However there don't seem to be any resources where you can easily get the logo from.  It is possible go the main site and extract the SVG if you're dedicated enough.  Would it be worthwhile including the logo in small range of formats in this repo?

**Comment by dantrauner** [comment]
Definitely – we'll decide on what formats we'd like to provide more conveniently (probably both SVG and some rasterized versions) and will PR adding those soon.

**Comment by dantrauner** [comment]
Closed with https://github.com/disclose/disclose/pull/11
